#Database Configuration
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DATABASE: sendEmailDemo
POSTGRES_SQL_USERNAME: seydina
POSTGRES_SQL_PASSWORD: root

#Server Configuration
CONTAINER_PORT: 8080
PROFILES_ACTIVE: dev

#Email Configuration
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <your-email>@gmail.com
EMAIL_PASSWORD: <your-email-password>
VERIFY_EMAIL_HOST: http://${POSTGRES_SQL_HOST}:${CONTAINER_PORT}

UI_APP_URL: localhost:4200
