#Database Configuration
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DATABASE: sendEmailDemo
POSTGRES_SQL_USERNAME: seydina
POSTGRES_SQL_PASSWORD: root

#Server Configuration
CONTAINER_PORT: 9000
PROFILES_ACTIVE: prod
